# Generated by Django 4.2.3 on 2024-02-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_due', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='april',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='august',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='december',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='february',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='january',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='july',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='june',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='march',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='may',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='november',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='october',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='september',
            name='date_paid',
            field=models.DateTimeField(editable=False),
        ),
    ]
