# Generated by Django 4.2.3 on 2024-02-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_due', '0002_alter_april_date_paid_alter_august_date_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='april',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='august',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='december',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='february',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='january',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='july',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='june',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='march',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='may',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='november',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='october',
            old_name='date_paid',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='september',
            old_name='date_paid',
            new_name='timestamp',
        ),
    ]
