# Generated by Django 4.2.3 on 2024-02-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_due', '0003_rename_date_paid_april_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='january',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
