# Generated by Django 4.2.3 on 2024-02-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_due', '0004_january_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='april',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='august',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='december',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='february',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='july',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='june',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='march',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='may',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='november',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='october',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='september',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
