# Generated by Django 4.2.3 on 2024-02-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_due', '0005_april_amount_august_amount_december_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='april',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='august',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='december',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='february',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='january',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='july',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='june',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='march',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='may',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='november',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='october',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='september',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
