# Generated by Django 4.2.3 on 2023-12-20 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Membership", "0002_alter_membership_verification_id_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership_verification",
            name="client_name",
            field=models.ForeignKey(
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
