# Generated by Django 4.2.3 on 2024-02-12 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0003_alter_membership_verification_client_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership_verification',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='membership_verification',
            name='date_sent_in',
        ),
        migrations.AddField(
            model_name='membership_verification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
