# Generated by Django 4.2.3 on 2024-03-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_available',
            field=models.BooleanField(default=False),
        ),
    ]
