# Generated by Django 4.2.3 on 2024-03-14 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_orderitems_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 23, 37, 19, 525511)),
        ),
    ]
