# Generated by Django 4.2.3 on 2024-03-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_order_review_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Comment',
        ),
    ]
