# Generated by Django 4.2.3 on 2024-03-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_rename_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
