# Generated by Django 4.2.3 on 2024-02-13 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_display_ads_ads_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='display_ads',
            name='ads_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='display_ads',
            name='ads_starts',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
