# Generated by Django 4.2.3 on 2024-02-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='your occupation', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='your occupation', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.ImageField(default='None', upload_to='profilePassports/'),
        ),
    ]
