# Generated by Django 4.2.3 on 2024-02-12 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Loan_Request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan_request_list',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='loan_request_list',
            name='date_submitted',
        ),
        migrations.AddField(
            model_name='loan_request_list',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
