# Generated by Django 4.2.3 on 2024-02-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inAppDonations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inappdonations',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='inappdonations',
            old_name='created',
            new_name='timestamp',
        ),
    ]
