# Generated by Django 4.2.3 on 2023-12-16 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment_for_Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default="0", editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False)),
                ("payment_purpose", models.CharField(max_length=200)),
                (
                    "payment_ref",
                    models.CharField(blank=True, editable=False, max_length=15),
                ),
                (
                    "client_name",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Withdrawal_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_id",
                    models.CharField(default="0", editable=False, max_length=200),
                ),
                ("account_name", models.CharField(default="0", max_length=200)),
                ("account_number", models.CharField(default="0", max_length=200)),
                ("bank_name", models.CharField(default="0", max_length=200)),
                ("date_of_request", models.DateTimeField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "client_name",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_bought", models.DateTimeField(auto_now_add=True)),
                (
                    "Share_return_at",
                    models.FloatField(
                        default=5, editable=False, help_text="Shares is at 5%"
                    ),
                ),
                (
                    "share_id",
                    models.CharField(default="0", editable=False, max_length=200),
                ),
                ("there_was_a_withdrawal", models.BooleanField(default=False)),
                (
                    "amount_bought",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Share.payment_for_share",
                    ),
                ),
                (
                    "client_name",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_bought"],
            },
        ),
    ]
