# Generated by Django 4.2.3 on 2024-02-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_for_share',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='shareholding',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='payment_for_share',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='shareholding',
            old_name='date_bought',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='withdrawal_request',
            old_name='date_of_request',
            new_name='timestamp',
        ),
    ]
